spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: abc12345
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
logging:
  level:
    root: info
    com.myblog: debug
  file: log/blog-dev.log


mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.myblog.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8089