spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: abc123456
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署

thymeleaf:
  mode=HTML:
    debug: true

logging:
  level:
    root: warn
    com.myblog: info
  file: log/blog-pro.log

server:
  port: 8081